#! /bin/sh
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $local_fs $remote_fs $syslog $named $network $time icinga
# Required-Stop:     $local_fs $remote_fs $syslog $named $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start and stop Icinga-Reporting daemon
# Description:       Icinga is a service monitoring system
### END INIT INFO

JASPERCTLSCRIPT="/usr/local/jasperreports-server-cp-5.5.0a/ctlscript.sh"

start()
{
	$JASPERCTLSCRIPT start
}
stop()
{
	$JASPERCTLSCRIPT stop
}
restart()
{
	$JASPERCTLSCRIPT restart
}
status()
{
	$JASPERCTLSCRIPT status
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
  status)
	status
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|status}"
	;;
esac
exit 1

EOCFG
