#! /bin/sh
### BEGIN INIT INFO
# Provides:          icinga-reporting
# Required-Start:    
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# chkconfig: 345 85 15
# Short-Description: start and stop Icinga-Reporting daemon
# Description:       Icinga is a service monitoring system
### END INIT INFO

JASPERCTLSCRIPT="/opt/jasperreports-server-cp-5.5.0/ctlscript.sh "

start()
{
	"$JASPERCTLSCRIPT" start postgres
}
stop()
{
	"$JASPERCTLSCRIPT" stop postgres
}
restart()
{
	$JASPERCTLSCRIPT restart postgres
}
status()
{
	$JASPERCTLSCRIPT status postgres
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
  status)
	status
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|status}"
	;;
esac
exit 1

EOCFG
